### PR TITLE
Revert Swiftlint version on Dockerfile to 0.46.1

### PR DESCRIPTION
**Pull request by f-meloni**

### CODE REVIEW

**Comment by Kiran-B** [comment]
@f-meloni Should we try this: https://github.com/danger/swift/pull/538#issuecomment-1278948517 before we revert?

**Comment by f-meloni** [comment]
Hey @Kiran-B.
I imagined it was a swift version issue, but I wanted to first fix the release, and the investigate it.
I can make another release like 3.14.3 immediately after :)

**Comment by Kiran-B** [comment]
Sure. Let me raise a fresh PR. Is there a way to verify the GH action without merging the PR?

**Comment by f-meloni** [comment]
you can run ` docker build .`

**Pull request merged**
