### PR TITLE
Gitlab Error in merge request with estimate or spent time

### PR DESCRIPTION
**Pull request by oscarcv**
The `humanTimeEstimate` and `humanTimeSpent` fields are parsed as `Int` and the api returns them as `String`.

An example of this format would be `1mo 2w 3d 4h 5m` ([Gitlab - Time Tracker Units](https://docs.gitlab.com/ee/user/project/time_tracking.html#available-time-units))

An example from the [official gitlab documentation](https://docs.gitlab.com/ee/api/merge_requests.html#set-a-time-estimate-for-a-merge-request):

```json
{
  "human_time_estimate": "3h 30m",
  "human_total_time_spent": null,
  "time_estimate": 12600,
  "total_time_spent": 0
}
```

Thank you

### CODE REVIEW

**Review by f-meloni — COMMENTED** [review]
Good catch!
Can you please also update the changelog?
As an addition having a unit test for this would be great, but I'm fine also without it

**Comment by oscarcv** [comment]
> Good catch! Can you please also update the changelog? As an addition having a unit test for this would be great, but I'm fine also without it

@f-meloni 

I have modified the tests to validate the type change and check the parse and I have also added the entry in the Changelog.

Thanks

**Comment by 417-72KI** [comment]
@oscarcv 
Can you please merge or rebase?
An linux runner on GitHub Actions has been updated and caused CI failure, resolved on #550.

**Comment by oscarcv** [comment]
> @oscarcv Can you please merge or rebase origin? 🙇 An linux runner on GitHub Actions has been updated and caused CI failure, resolved on #550.

@417-72KI  Merged from origin

**Pull request merged**
