### PR TITLE
Update copyright notice to 2019

### PR DESCRIPTION
**Pull request by Atul9**

### CODE REVIEW

**Comment by f-meloni** [comment]
thank you :)

**Comment by f-meloni** [comment]
Looking at https://github.com/danger/danger/blob/master/LICENSE i think it should be just 2019 :)

**Comment by Atul9** [comment]
I think for https://github.com/danger/danger/blob/master/LICENSE it should be updated to 2015-2019, it states from when to which year the project is copyrighted. 
Like this one - https://github.com/danger/danger-js/blob/master/LICENSE

**Comment by f-meloni** [comment]
Ok :) I will tag @orta, just to double check he is happy with the change, otherwise we can revert it 👍

**Comment by orta** [comment]
Yeah, I don't really mind - strictly speaking licenses only need their initial year of creation but I'm happy for other folks to keep the numbers up to date

**Pull request merged**
