### PR TITLE
Fix a decode error with BitBucket server

### PR DESCRIPTION
**Pull request by pepix**
# Issue

I faced a decode error when I run `$ danger-swift pr <pr_url>` for a certain pull request in GitBucket Server.
As my investigation, it seems they don't return `public` field if that repository is forked by someone.
After I made it optional, it works.

error

> ERROR: Failed to parse JSON: keyNotFound(CodingKeys(stringValue: "public", intValue: nil), Swift.DecodingError.Context(codingPath: [CodingKeys(stringValue: "danger", intValue: nil), CodingKeys(stringValue: "bitbucket_server", intValue: nil), CodingKeys(stringValue: "pr", intValue: nil), CodingKeys(stringValue: "fromRef", intValue: nil), CodingKeys(stringValue: "repository", intValue: nil), CodingKeys(stringValue: "project", intValue: nil)], debugDescription: "No value associated with key CodingKeys(stringValue: \"public\", intValue: nil) (\"public\").", underlyingError: nil))

> ERROR: Dangerfile eval failed at Dangerfile.swift
ERROR: Could not get the results JSON file at /var/folders/__/clhhlm6d5fg7__h0syj9vmtw0000gv/T/danger-response.json

### CODE REVIEW

**Review by f-meloni — APPROVED** [review]
Thank you!
Could you please add a test for this? (not a blocker)

**Comment by pepix** [comment]
I can't find why CI failed though got no errors locally..

**Comment by pepix** [comment]
Posted issue since I found an issue on CI pipeline https://github.com/danger/swift/issues/556

**Comment by f-meloni** [comment]
I have made few changes to reduce the noise made from swiftlint and swiftformat, I will merge this so that it can make it in the release and work on swiftlint as a separated issue.

**Pull request merged**
