### PR TITLE
fix/fix-broken-edit

### PR DESCRIPTION
**Pull request by lucasmpaim**
In my computer using the last one xcode on a mac os Catalina, I can't use the `danger-swift edit` because it's generate a wrong swift tools version.

This is because the function `resolveSwiftToolsVersion` only remove the prefix: "Apple Swift Package Manager - Swift ", but in my computer the command `swift package --version` get an output:

```bash
Swift Package Manager - Swift 5.2.0
```

Without the "Apple " prefix, because this I got an error like this:
```
ERROR: commandFailed(command: "<.....>Dangerfile\' is using Swift tools version 0.0.0 which is no longer supported; consider using \'// swift-tools-version:5.2\' to specify the current tools version\n")
```

Using the new `onlyNumbersAndDots` extension, it's a more safe form to extract the version of swift package manager.

### CODE REVIEW

**Comment by danger-public** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>

   Any changes to library code should be reflected in the Changelog.

 Please consider adding a note there and adhere to the [Changelog Guidelines](https://github.com/Moya/contributors/blob/master/Changelog%20Guidelines.md).
  </td>
    </tr>
  </tbody>
</table>



<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/swift">Danger Swift</a> against bebc19e4968a346e747cf2adfc3befe17ed8f9a7
</p>

**Comment by lucasmpaim** [comment]
> Thank you, this is really great, but I have a small suggestion, you could make this a lot more efficient by using a charset.
> 
> e.g.
> 
> ```swift
> var charset = CharacterSet.decimalDigits
> charset.insert(".")
> 
> return = String(unicodeScalars.filter(charset.contains))
> ```

Great, this is better than an regex check, I have updated the extension, thanks :)

**Comment by orta** [comment]
Clever work

**Comment by lucasmpaim** [comment]
For some reason travis is getting:

```
unable to access 'https://github.com/kareman/SwiftShell/': Failed to connect to github.com port 443: Operation timed
```

I don't think this is something that I have changed....

**Pull request merged**
